export default [
  { text: "Course Introduction", link: "/intro/" },
  { text: "Setting Up", link: "/setting/" },
  { text: "The Node Binary", link: "/binary/" },
  { text: "Debugging & Diagnostics", link: "/debug/" },
  { text: "Key JavaScript Concepts", link: "/javascript/" },
  { text: "Packages & Dependencies", link: "/package/" },
  { text: "Node’s Module System", link: "/module/" },
  { text: "Asynchronous Control Flow", link: "/async/" },
  { text: "Node’s Event System", link: "/event/" },
  { text: "Handling Errors", link: "/error/" },
  { text: "Using Buffers", link: "/buffer/" },
  { text: "Working with Streams", link: "/stream/" },
  { text: "Interacting with File System", link: "/fs/" },
  { text: "Process & Operating System", link: "/os/" },
  { text: "Creating Child Processes", link: "/child-process/" },
  { text: "Writing Unit Tests", link: "/unit-test/" },
];
